### PR TITLE
fix(es,ts): remove posibility to create unused vars

### LINKED ISSUE #20: [Rules | ES, TS]: 'naming-convention' and 'no-unused-vars' doesn't work together
I can't write code like that:
```
const _exhaustiveCheck: never = value;
```

Error "Variable name `_exhaustiveCheck` must match one of the following formats: camelCase, UPPER_CASE" appears.
After deleting `_` appears another error "'exhaustiveCheck' is assigned a value but never used. Allowed unused vars must match /^_/u"

### PR DESCRIPTION
**Pull request by sashaqred**
By default rule allow unused arguments `"args": "after-used"`:
```js
//         ⬇️ no error, because `index` is used
[].filter((item, index, array) => {
//                      ⬆️ eslint error of unused var
  console.log(index);
});
```

Also by default eslint will throw error on `foo`:
```js
const { foo, ...coords } = data;
```
Looks useful feature, to skip keys in object. So I configure rules to make this works.

And the last thing where unused variables are useful:
```
const [one, two, three] = [1, 2, 3];
console.log(one, three);
```
I couldn't find how to configure it properly. But in js there is a workaround:
```
//         ⬇️ second item is missed, not beautiful but as is
const [one, , three] = [1, 2, 3];
console.log(one, three);
```
I think it's not critical for the first release

Closes #20

### CODE REVIEW

**Review by zankevich — APPROVED** [review]

File: rules/typescript.js [hunk 1]
```diff
@@ -4,12 +4,7 @@ const rules = {
   '@typescript-eslint/ban-ts-comment': ['error', {'ts-ignore': 'allow-with-description'}],
 
   'no-unused-vars': 'off',
-  '@typescript-eslint/no-unused-vars': ['error',
-    {
-      argsIgnorePattern: '^_',
-      varsIgnorePattern: '^_',
-      ignoreRestSiblings: true,
-    }], // TODO: add to styleguide exception regarding args starting with _
+  '@typescript-eslint/no-unused-vars': ['error', { 'ignoreRestSiblings': true }],
```
Comment (malashkevich) [inline rules/typescript.js:7]: Please change accordingly `typescript.md` in the Naming Style section:

https://github.com/akveo/styleguide/blob/master/typescript.md#naming-style-

**Review by malashkevich — CHANGES_REQUESTED** [review]

File: rules/typescript.js (hunk 1 above)
Comment (sashaqred) [reply rules/typescript.js:7]: I've updated it

**Review by malashkevich — APPROVED** [review]
